---
global:
templates:
- '/etc/alertmanager/template/*.tmpl'
route:
  repeat_interval: 1m
  receiver: operations-team

receivers:
- name: 'operations-team'
  slack_configs:
  - api_url: https://hooks.slack.com/services/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
    channel: '#alert'
    send_resolved: true

